### ISSUE TITLE
[ERRO] comment out that line or remove the same error. other than that it's all ok on it I'm testing on void-linux and so far no bugs. I'm already creating scripts to install more programs.

### ISSUE THREAD

**Issue by walber-vaz** [emmett1/alicelinux#5]
https://github.com/emmett1/alicelinux/blob/ee9cc4b05b097cfe379e64070f1bf91491f2eb1b/scripts/pkg.sh#L20

**Comment by emmett1** [comment]
ops sorry my bad, forgot to remove that line. i'm gonna push the fix again later with all script changes. btw thanks for your report and help. just make PR anytime of your changes.

**Comment by walber-vaz** [comment]
ok i'm doing it here too as soon as it is good installation scripts send in the pull.
Sorry my English I am from Brazil I don't speak very well ... the distro is getting good.

**Comment by emmett1** [comment]
its ok, my english not good too.
i'm already fix this issue and push.

**Comment by walber-vaz** [comment]
Ok
